name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache cargo
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Install nextest
      run: cargo install cargo-nextest--version 0.9.124  --locked

    - name: Build logic
      working-directory: ./logic
      run: cargo build --verbose

    - name: Run tests (nextest)
      working-directory: ./logic
      run: cargo nextest run --verbose

    - name: Build examples rp
      working-directory: ./example/rp
      run: cargo build --verbose

    - name: Build examples rp235
      working-directory: ./example/rp235
      run: cargo build --verbose
